###
GET http://localhost:8080/api/locations

###
GET http://localhost:8080/api/location/1

###
POST http://localhost:8080/api/planner
Content-Type: application/x-www-form-urlencoded

description=Fourth Planner Description&name=Fourth Planner&locationList=

###
POST http://localhost:8080/api/planner/new
Content-Type: application/json

{"name": "Second Planner Check", "description": "Second Planner Description", "locationList" : []}

###
PUT http://localhost:8080/api/edit/planner/6
Content-Type: application/json

{"name": "Sixth Planner Check", "description": "Sixth Planner Description", "locationList" : []}

###
GET http://localhost:8080/api/planners

###
GET http://localhost:8080/api/planner/1

###
GET http://localhost:8080/api/city/locations?cityId=1&companionId=1&lengthOfStay=1&categoryIds=1,2

###
GET http://localhost:8080/api/region/locations?regionId=1&companionId=1&lengthOfStay=1&categoryIds=1,2

###
GET http://localhost:8080/api/companions

###
GET http://localhost:8080/api/categories

###
GET http://localhost:8080/api/regions

###
GET http://localhost:8080/api/cities

###
GET http://localhost:8080/api/countries

###
PUT http://localhost:8080/api/add-location
Content-Type: application/json

{"plannerId": 1, "locationId": 2}

###
GET http://localhost:8080/api/planner/locations?plannerId=1
Content-Type: application/x-www-form-urlencoded

###
GET http://localhost:8080/api/planner/locationIds?plannerId=2
Content-Type: application/x-www-form-urlencoded

###
GET http://localhost:8080/api/weekend
Content-Type: application/x-www-form-urlencoded

###
GET http://localhost:8080/api/villages
Content-Type: application/x-www-form-urlencoded

###
GET http://localhost:8080/api/images?locationId=1
Content-Type: application/x-www-form-urlencoded